### ISSUE TITLE
文档翻译：https://istio.io/docs/reference/config/mixer/expression-language.html

### ISSUE THREAD

**Issue by rootsongjc** [doczhcn/istio#136]
文档翻译：https://istio.io/docs/reference/config/mixer/expression-language.html
Expression Language

**Comment by lsytj0413** [comment]
这个是等待翻译还是已经翻译完成了？

**Comment by rootsongjc** [comment]
@lsytj0413 这个仓库已经不在维护，你可以直接向Istio官方文档提交PR，官方文档已经开始中文版本支持。

**Comment by lsytj0413** [comment]
那建议在仓库的说明上标明不再维护吧

**Comment by rootsongjc** [comment]
被仓库已经停止维护，请移步[Istio官方仓库](https://github.com/istio/istio.github.io)。
