### ISSUE TITLE
文档翻译:Tasks-Traffic Management

### ISSUE THREAD

**Issue by skyao** [doczhcn/istio#18]
https://istio.io/docs/tasks/traffic-management/

**Comment by fleeto** [comment]
hmm

**Comment by zhaohuabing** [comment]
Hi, Skyao,

How could I assign this task to myself?

Thanks,
Huabing

**Comment by node** [comment]
注意：本任务已拆分为多个小任务，无需认领此任务。 待task-traffic章节的全部小任务完成后，即可关闭。
