### ISSUE TITLE
文档翻译:Setup-Kubernetes

### ISSUE THREAD

**Issue by rootsongjc** [doczhcn/istio#6]
如题，Setup部分缺失

**Comment by skyao** [comment]
https://istio.io/docs/setup/kubernetes/

**Comment by rootsongjc** [comment]
翻译完成得部分统计如下：

- [x] 2. 安装

- [x] 2.1 Kubernetes
  - [x] 2.1.1 快速开始
  - [ ] 2.1.2 安装 Istio sidecar
  - [ ] 2.1.3 Istio Mesh 扩张
  - [ ] 2.1.4 FAQ
- [x] 2.2 Nomad 和 Consul
  - [ ] 2.2.1 使用 Docker 快速开始
  - [ ] 2.2.2 安装
  - [ ] 2.2.3 FAQ
- [x] 2.3 Eureka
  - [ ] 2.3.1 使用 Docker 快速开始
  - [ ] 2.3.2 安装
  - [ ] 2.3.3 FAQ
- [x] 2.4 Cloud Foundry
  - [x] 2.4.1 安装
- [x] 2.5 Mesos
  - [x] 2.5.1 安装

**Comment by rootsongjc** [comment]
在Kubernetes中安装Istio部分翻译完成。
