### ISSUE TITLE
sidecar等名词翻译问题

### ISSUE THREAD

**Issue by chinaboard** [doczhcn/istio#92]
在文档概述部分，sidecar被直译为边车，在后续的文档中，有些地方直接保留了sidecar的写法
个人建议相关名词最好先不要翻译，或者翻译后括号加上原文，方便辨识

**Comment by rootsongjc** [comment]
这个词建议还是不翻译的好。

**Comment by chinaboard** [comment]
是的，建议做个列表，这样大家遇到的时候可以统一一下

**Comment by skyao** [comment]
已经在翻译说明中添加Sidecar为不翻译。

http://istio.doczh.cn/translation.html

非常感谢你的建议！
