### ISSUE TITLE
检查文档更新：setup部分

### ISSUE THREAD

**Issue by skyao** [doczhcn/istio#95]
检查0.5.0版本发布之后的文档更新，对比目前我们已经翻译的0.2.0版本

- 官方版本地址： https://istio.io/docs/setup/
- 翻译版本地址： http://istio.doczh.cn/docs/setup/

注意这个任务是检查文档是否有更新：

- 如果文档内容没有更新，请在下面备注说明内容没有改动，直接close这个issue
- 如果文档内容有更新
    - 如果只是少量简单内容更新，请在检查时随手修改，提交时请关联到这个issue
    - 如果有比较多的改动内容，请在这里备注有哪些有大改动
    - 为每个大改的章节单独再开一个issue，标签请选择"type/translation"

**Comment by DavadDi** [comment]
@skyao 这个我来认领吧

**Comment by DavadDi** [comment]
新增加章节：
1. Quick Start with Google Kubernetes Engine 参见：https://github.com/doczhcn/istio/issues/101
